// Generated by voltages_16bit.py on 06/11/14 21:10:32.

#ifndef __VOLTAGES_H__
#define __VOLTAGES_H__

#define NUM_REF_TABLES 16
#define NUM_VOLTAGES_PER_TABLE 100
#define REF_TABLE_SEMITONES 0
#define REF_TABLE_LINEAR 5
#define CODE_TO_VOLTAGE(x) (x >> 3)
#define VOLTAGE_TO_CODE(x) (x << 3)
#define CODE_PER_OCTAVE 8000
#define CODE_FOR_C 0
#define CODE_FOR_D 1333
#define CODE_FOR_E 2667
#define CODE_FOR_F 3333
#define CODE_FOR_G 4667
#define CODE_FOR_A 6000
#define CODE_FOR_B 7333

extern const uint16_t ref_tables[NUM_REF_TABLES][NUM_VOLTAGES_PER_TABLE];
extern const bool ref_table_is_pitched[NUM_REF_TABLES];
extern const bool ref_table_can_edit[NUM_REF_TABLES];
extern const uint16_t ref_table_name_left[NUM_REF_TABLES];
extern const uint16_t ref_table_name_right[NUM_REF_TABLES];
extern const uint8_t wholetone[201];

#endif // __VOLTAGES_H__